apiVersion: v1
kind: Service
metadata:
  name: python-k8s-app-service
  namespace: python-k8s-app
  labels:
    app: python-k8s-app
spec:
  selector:
    app: python-k8s-app
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: python-k8s-app-service-nodeport
  namespace: python-k8s-app
  labels:
    app: python-k8s-app
spec:
  selector:
    app: python-k8s-app
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  type: NodePort
